name : Excel file automation with python

on : 
  schedule : 
    - cron : '47 9 * * *'
jobs : 
  update_commit : 
    runs-on : ubuntu_latest
    steps : 
       - name : checking the code
         uses : actions/checkout@v2
       - name : Python 
         uses: actions/setup-python@v2
         with : 
            python-version : '3.8'
       - name : library installation 
         run : |
          pip installation gitpython openpyxl datetime pytz
       - name : automation
         run: python commit_excel_file.py  
            

   
